=== jwbullard/THAMES/tests/portcem-298K-sat-wc45/chemistry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- definition of simple types -->
  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="integertype">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <xs:simpleType name="positiveIntegertype">
    <xs:restriction base="xs:positiveInteger"/>
  </xs:simpleType>

  <xs:simpleType name="doubletype">
    <xs:restriction base="xs:double"/>
  </xs:simpleType>

  <xs:simpleType name="positiveDoubletype">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="kineticTypetype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="kinetic"/>
      <xs:enumeration value="soluble"/>
      <xs:enumeration value="thermo"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="elementtype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="K"/>
      <xs:enumeration value="Na"/>
      <xs:enumeration value="S"/>
      <xs:enumeration value="Al"/>
      <xs:enumeration value="C"/>
      <xs:enumeration value="Ca"/>
      <xs:enumeration value="Si"/>
      <xs:enumeration value="Mg"/>
      <xs:enumeration value="Fe"/>
      <xs:enumeration value="P"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="O"/>
      <xs:enumeration value="Cl"/>
      <xs:enumeration value="F"/>
      <xs:enumeration value="Li"/>
      <xs:enumeration value="B"/>
      <xs:enumeration value="Cr"/>
      <xs:enumeration value="Mn"/>
      <xs:enumeration value="Co"/>
      <xs:enumeration value="Sr"/>
      <xs:enumeration value="Ba"/>
      <xs:enumeration value="Y"/>
      <xs:enumeration value="Ti"/>
      <xs:enumeration value="Be"/>
      <xs:enumeration value="Nb"/>
      <xs:enumeration value="Cd"/>
      <xs:enumeration value="Zn"/>
      <xs:enumeration value="Sc"/>
      <xs:enumeration value="Cu"/>
      <xs:enumeration value="V"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of complex types -->
  <xs:complexType name="iccomptype">
    <xs:sequence>
      <xs:element name="name" type="stringtype"/>
      <xs:element name="conc" type="doubletype"/>
    </xs:sequence>
  </xs:complexType>
   
  <xs:complexType name="solutioncomptype">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ICcomp" type = "iccomptype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="affinitytype">
    <xs:sequence>
      <xs:element name="affinityphase" type="stringtype"/>
      <xs:element name="affinityvalue" type="integertype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType mixed="true" name="interface_datatype">
    <xs:sequence>
      <xs:element name="randomgrowth" type="doubletype"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="affinity" type="affinitytype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType mixed="true" name="impurity_datatype">
    <xs:sequence>
      <xs:element name="k2ocoeff" type="positiveDoubletype"/>
      <xs:element name="na2ocoeff" type="positiveDoubletype"/>
      <xs:element name="mgocoeff" type="positiveDoubletype"/>
      <xs:element name="so3coeff" type="positiveDoubletype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType mixed="true" name="Rdtype">
    <xs:sequence>
      <xs:element name="Rdelement" type="elementtype"/>
      <xs:element name="Rdvalue" type="positiveDoubletype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType mixed = "true" name="kinetic_datatype">
    <xs:sequence>
      <xs:element name="type" type="kineticTypetype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="scaledmass" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="k1" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="k2" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="k3" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="n1" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="n3" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="Ea" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="critdoh" type="positiveDoubletype"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Rd" type="Rdtype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="display_datatype">
    <xs:sequence>
      <xs:element name="red" type="positiveDoubletype"/>
      <xs:element name="green" type="positiveDoubletype"/>
      <xs:element name="blue" type="positiveDoubletype"/>
      <xs:element name="gray" type="positiveDoubletype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="gemdc_datatype">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="gemdcname" type="stringtype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="gemdcporosity" type="stringtype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="gemphase_datatype">
    <xs:sequence>
      <xs:element name="gemphasename" type="stringtype"/>
      <xs:element maxOccurs="unbounded" name="gemdc" type="gemdc_datatype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="phasetype">
    <xs:sequence>
      <xs:element name="thamesname" type="stringtype"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="gemphase_data" type="gemphase_datatype"/>
      <xs:element name="id" type="integertype"/>
      <xs:element minOccurs="0" name="interface_data" type="interface_datatype"/>
      <xs:element minOccurs='0' maxOccurs="1" name="poresizefilename" type="stringtype"/>
      <xs:element minOccurs="0" name="impurity_data" type="impurity_datatype"/>
      <xs:element minOccurs="0" name="kinetic_data" type="kinetic_datatype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="stresscalc" type="integertype"/>
      <xs:element minOccurs="0" maxOccurs="1" name="weak" type="integertype"/>
      <xs:element name="display_data" type="display_datatype"/>
    </xs:sequence>
  </xs:complexType>

  <!-- definition of root element -->

  <xs:element name="chemistry_data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numentries" type="positiveIntegertype"/>
        <xs:element name="blaine" type="positiveDoubletype"/>
        <xs:element name="refblaine" type="positiveDoubletype"/>
        <xs:element minOccurs="0" maxOccurs="1" name="wcRatio" type="positiveDoubletype"/>
        <xs:element name="temperature" type="positiveDoubletype"/>
        <xs:element name="reftemperature" type="positiveDoubletype"/>
        <xs:element name="saturated" type="integertype"/>
        <xs:element minOccurs="0" maxOccurs="1" name="solution" type="solutioncomptype"/>
        <xs:element maxOccurs="unbounded" name="phase" type="phasetype"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jwbullard/THAMES/tests/alite-298K-sealed-wc35/chemistry.xml
<?xml version="1.0" encoding="UTF-8"?>
<chemistry_data xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="/Users/bullard/Software/MyProjects/THAMES/src/xsdfiles/chemistry.xsd">
  <!--The number of possible phases in the microstructure not counting Void-->
  <numentries>5</numentries>
  <!--Temperature in K-->
  <temperature>298.15</temperature>
  <!--Do not change next value, used for Parrott and Killoh kinetic model-->
  <reftemperature>296.15</reftemperature>
  <!--Set to 1 for saturated, 0 for sealed-->
  <saturated>0</saturated>
  <!--Information for initial solution IC composition besides water, each in mol/kgw-->
  <solution>
      <ICcomp>
          <name>Ca</name>
          <conc>0.001</conc>
      </ICcomp>
      <ICcomp>
          <name>K</name>
          <conc>0.001</conc>
      </ICcomp>
      <ICcomp>
          <name>S</name>
          <conc>0.0005</conc>
      </ICcomp>
      <ICcomp>
          <name>O</name>
          <conc>0.004</conc>
      </ICcomp>
      <ICcomp>
          <name>H</name>
          <conc>0.002</conc>
      </ICcomp>
  </solution>

  <!--Void phase should always be present and first in the list-->
  <phase>
    <thamesname>Void</thamesname>
    <!--Unique integer id for microstructure phase-->
    <id>0</id>
    <!--Interface data not used for void phase-->
    <interface_data>
      <randomgrowth>0.0</randomgrowth>
    </interface_data>
    <!--Display rgb colors, 0 to 255-->
    <display_data>
        <red>0.0</red>
        <green>0.0</green>
        <blue>0.0</blue>
        <gray>0.0</gray>
    </display_data>
  </phase>
  <!--Water phase should always be present and  in the list-->
  <phase>
    <thamesname>Electrolyte</thamesname>
    <!--Which GEM phase(s) and DC(s) are linked to this microstructure phase?-->
    <gemphase_data>
      <gemphasename>aq_gen</gemphasename>
      <gemdc>
        <gemdcname>H2O@</gemdcname>
        <gemdcporosity>1.0</gemdcporosity>
      </gemdc>
    </gemphase_data>
    <id>1</id>
    <!--Interface data not used for void phase-->
    <interface_data>
      <randomgrowth>0.0</randomgrowth>
    </interface_data>
    <display_data>
      <red>25.0</red>
      <green>25.0</green>
      <blue>25.0</blue>
      <gray>25.0</gray>
    </display_data>
  </phase>
  <phase>
    <thamesname>Alite</thamesname>
    <gemphase_data>
      <gemphasename>Alite</gemphasename>
      <gemdc>
        <gemdcname>C3S</gemdcname>
      </gemdc>
    </gemphase_data>
    <id>2</id>
    <!--Solid phases have meaningful interface data-->
    <interface_data>
        <!--randomgrowth between 0 and 1, 1 is totally random attachment
            or detachment, 0 means interface mean curvature governs the
        attachment and detachment points-->
      <randomgrowth>0.0</randomgrowth>
      <!--Affinity is the relative strength of the attraction between this phase
          and a template phase.  If a template is not listed, it takes the default
          value of 0.  Positive numbers indicate attraction and negative numbers
      mean repulsion-->
      <affinity>
        <affinityphase>Alite</affinityphase>
        <affinityvalue>1</affinityvalue>
      </affinity>
    </interface_data>
    <!--We can specify minority impurity concentrations in a solid phase, which
    will be released in proportion during dissolution-->
    <impurity_data>
        <k2ocoeff>0.00087</k2ocoeff>  <!--K2O mole fraction-->
        <na2ocoeff>0.0</na2ocoeff>    <!--Na2O mole fraction-->
        <mgocoeff>0.00861</mgocoeff>    <!--MgO mole fraction-->
        <so3coeff>0.007942</so3coeff>   <!--SO3 mole fraction-->
    </impurity_data>
    <kinetic_data>
      <!--Type is whether the phase is controlled by kinetics or thermodynamics-->
      <type>ParrotKilloh</type>
      <specificSurfaceArea>402.0</specificSurfaceArea>
      <refSpecificSurfaceArea>385.0</refSpecificSurfaceArea>

      <!--k1, k2, k3, n1, n3 are Parrott and Killoh parameters. Do not change-->
      <k1>1.5</k1>
      <k2>0.05</k2>
      <k3>1.1</k3>
      <n1>0.7</n1>
      <n3>3.3</n3>
      <!--Ea is the apparent activation energy for dissolution-->
      <Ea>41570.0</Ea>
      <!--critdoh is another P&K parameter-->
      <critdoh>2.0</critdoh>
    </kinetic_data>
    <display_data>
      <red>162.0</red>
      <green>117.0</green>
      <blue>95.0</blue>
      <gray>220.0</gray>
    </display_data>
  </phase>
  <phase>
    <thamesname>Portlandite</thamesname>
    <gemphase_data>
    <gemphasename>Portlandite</gemphasename>
    <gemdc>
      <gemdcname>Portlandite</gemdcname>
    </gemdc>
    </gemphase_data>
    <id>3</id>
    <interface_data>
      <randomgrowth>0.6</randomgrowth>
      <affinity>
        <affinityphase>Portlandite</affinityphase>
        <affinityvalue>1</affinityvalue>
      </affinity>
      <affinity>
          <affinityphase>CSHQ</affinityphase>
        <affinityvalue>1</affinityvalue>
      </affinity>
      <affinity>
        <affinityphase>Alite</affinityphase>
        <affinityvalue>-10</affinityvalue>
      </affinity>
    </interface_data>
    <display_data>
      <red>0.0</red>
      <green>0.0</green>
      <blue>255.0</blue>
      <gray>186.0</gray>
    </display_data>
  </phase>
  <phase>
    <thamesname>CSHQ</thamesname>
    <gemphase_data>
      <gemphasename>CSHQ</gemphasename>
      <gemdc>
        <gemdcname>CSHQ-JenD</gemdcname>
        <gemdcporosity>0.4935</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-JenH</gemdcname>
        <gemdcporosity>0.4935</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-TobD</gemdcname>
        <gemdcporosity>0.2004</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-TobH</gemdcname>
        <gemdcporosity>0.2004</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>KSiOH</gemdcname>
        <gemdcporosity>0.1825</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>NaSiOH</gemdcname>
        <gemdcporosity>0.1825</gemdcporosity>
      </gemdc>
    </gemphase_data>
    <id>4</id>
    <interface_data>
      <randomgrowth>0.995</randomgrowth>
      <affinity>
        <affinityphase>CSHQ</affinityphaseid>
        <affinityvalue>1</affinityvalue>
      </affinity>
      <affinity>
        <affinityphaseid>Alite</affinityphaseid>
        <affinityvalue>4</affinityvalue>
      </affinity>
    </interface_data>
    <poresizefilename>CSH-PoreSizeDistribution.csv</poresizefilename>
    <Rd>
      <Rdelement>K</Rdelement>
      <Rdvalue>0.42</Rdvalue>
    </Rd>
    <Rd>
      <Rdelement>Na</Rdelement>
      <Rdvalue>0.42</Rdvalue>
    </Rd>
    <display_data>
      <red>245.0</red>
      <green>222.0</green>
      <blue>179.0</blue>
      <gray>159.0</gray>
    </display_data>
  </phase>
</chemistry_data>

=== jwbullard/THAMES/tests/portcem-298K-sat-wc45_v3.0.0/chemtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<chemistry_data xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="chemistry.xsd">
  <!--The number of possible phases in the microstructure not counting Void-->
  <numentries>18</numentries>
  <!--Temperature in K-->
  <temperature>298.15</temperature>
  <!--Do not change next value, used for Parrott and Killoh kinetic model-->
  <reftemperature>298.15</reftemperature>
  <!--Set to 1 for saturated, 0 for sealed-->
  <saturated>1</saturated>
  <!--Void phase should always be present and first in the list-->
  <phase>
    <thamesname>Void</thamesname>
    <!--Unique integer id for microstructure phase-->
    <id>0</id>
    <!--This microstructure phase is not a cement component (value = 0; if yes, value = 1)-->
    <cement_component>0</cement_component>
    <!--Display rgb colors, 0 to 255 (set by default => optional)-->
    <display_data>
      <red>0.0</red>
      <green>0.0</green>
      <blue>0.0</blue>
      <gray>0.0</gray>
    </display_data>
  </phase>
  <phase>
    <thamesname>Alite</thamesname>
    <id>2</id>
    <cement_component>1</cement_component>
    <interface_data></interface_data>
    <gemphase_data>
      <gemphasename>Alite</gemphasename>
      <gemdc>
        <gemdcname>C3S</gemdcname>
      </gemdc>
    </gemphase_data>
    <impurity_data>
      <k2ocoeff>0.00087</k2ocoeff>
      <na2ocoeff>0.0</na2ocoeff>
      <mgocoeff>0.00861</mgocoeff>
      <so3coeff>0.007942</so3coeff>
    </impurity_data>
    <kinetic_data>
      <type>ParrotKilloh</type>
      <specificSurfaceArea>402.0</specificSurfaceArea>
      <refSpecificSurfaceArea>385.0</refSpecificSurfaceArea>
      <k1>1.5</k1>
      <k2>0.05</k2>
      <k3>1.1</k3>
      <n1>0.7</n1>
      <n3>3.3</n3>
      <dorHcoeff>2.0</dorHcoeff>
      <!--Apparent activation energy for dissolution - another P&K parameter-->
      <activationEnergy>41570.0</activationEnergy>
      <loi>0.0</loi>
    </kinetic_data>
  </phase>
  <phase>
    <thamesname>CSHQ</thamesname>
    <id>11</id>
    <cement_component>0</cement_component>
    <interface_data>
      <affinity>
        <affinityphase>Alite</affinityphase>
        <contactanglevalue>30</contactanglevalue>
      </affinity>
      <affinity>
        <affinityphase>Belite</affinityphase>
        <contactanglevalue>30</contactanglevalue>
      </affinity>
    </interface_data>
    <gemphase_data>
      <gemphasename>CSHQ</gemphasename>
      <gemdc>
        <gemdcname>CSHQ-JenD</gemdcname>
        <gemdcporosity>0.4935</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-JenH</gemdcname>
        <gemdcporosity>0.4935</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-TobD</gemdcname>
        <gemdcporosity>0.2004</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>CSHQ-TobH</gemdcname>
        <gemdcporosity>0.2004</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>KSiOH</gemdcname>
        <gemdcporosity>0.1825</gemdcporosity>
      </gemdc>
      <gemdc>
        <gemdcname>NaSiOH</gemdcname>
        <gemdcporosity>0.1825</gemdcporosity>
      </gemdc>
    </gemphase_data>
    <poresizefilename>CSH-PoreSizeDistribution.csv</poresizefilename>
    <Rd>
      <Rdelement>K</Rdelement>
      <Rdvalue>0.41999999</Rdvalue>
    </Rd>
    <Rd>
      <Rdelement>Na</Rdelement>
      <Rdvalue>0.41999999</Rdvalue>
    </Rd>
  </phase>
</chemistry_data>
