=== jwbullard/THAMES/src/xsdfiles/parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- definition of simple types -->
<xs:simpleType name="doubletype">
  <xs:restriction base="xs:double"/>
</xs:simpleType>

<xs:simpleType name="positiveDoubletype">
  <xs:restriction base="xs:double">
    <xs:minInclusive value="0"/>
  </xs:restriction>
</xs:simpleType>

<!-- definition of root element -->

<xs:element name="simulation_parameters">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="calctime" type="positiveDoubletype"/>
      <xs:element name="image_frequency" type="positiveDoubletype"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== jwbullard/THAMES/sample-input/obsolete-inputfiles-01/parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation_parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="/Users/bullard/thames_wd/parameters.xsd">
<calctime>	0.001	</calctime>
<calctime>	0.004	</calctime>
<calctime>	0.007	</calctime>
<calctime>	0.01	</calctime>
<calctime>	0.013	</calctime>
<calctime>	0.016	</calctime>
<calctime>	0.019	</calctime>
<calctime>	0.022	</calctime>
<calctime>	0.025	</calctime>
<calctime>	0.028	</calctime>
<calctime>	0.031	</calctime>
<calctime>	0.034	</calctime>
<calctime>	0.037	</calctime>
<calctime>	0.04	</calctime>
<calctime>	0.043	</calctime>
<calctime>	0.046	</calctime>
<calctime>	0.049	</calctime>
<calctime>	0.052	</calctime>
<calctime>	0.055	</calctime>
<calctime>	0.058	</calctime>
<calctime>	0.061	</calctime>
<calctime>	0.064	</calctime>
<calctime>	0.067	</calctime>
<calctime>	0.07	</calctime>
<calctime>	0.073	</calctime>
<calctime>	0.076	</calctime>
<calctime>	0.079	</calctime>
<calctime>	0.082	</calctime>
<calctime>	0.085	</calctime>
<calctime>	0.088	</calctime>
<calctime>	0.091	</calctime>
<calctime>	0.094	</calctime>
<calctime>	0.097	</calctime>
<calctime>	0.1	</calctime>
<calctime>	0.103	</calctime>
<calctime>	0.106	</calctime>
<calctime>	0.109	</calctime>
<calctime>	0.112	</calctime>
<calctime>	0.115	</calctime>
<calctime>	0.118	</calctime>
<calctime>	0.121	</calctime>
<calctime>	0.124	</calctime>
<calctime>	0.127	</calctime>
<calctime>	0.13	</calctime>
<calctime>	0.133	</calctime>
<calctime>	0.136	</calctime>
<calctime>	0.139	</calctime>
<calctime>	0.142	</calctime>
<calctime>	0.145	</calctime>
<calctime>	0.148	</calctime>
<calctime>	0.151	</calctime>
  <image_frequency>1.0</image_frequency>
</simulation_parameters>

=== jwbullard/THAMES/tests/pyrrcem-298K-sat_v3.0.0/parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation_parameters xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
  xs:noNamespaceSchemaLocation="https://github.tamu.edu/jwbullard/THAMES/blob/master/src/thameslib/xsdfiles/parameters.xsd">
 <calctime>0.001</calctime>
 <calctime>0.0011</calctime>
 <calctime>0.00121</calctime>
 <calctime>0.001331</calctime>
 <calctime>0.0014641</calctime>
 <calctime>0.00161051</calctime>
 <calctime>0.00177156</calctime>
 <calctime>0.00194872</calctime>
 <calctime>0.00214359</calctime>
 <calctime>0.00235795</calctime>
 <calctime>0.00259374</calctime>
 <calctime>0.00285312</calctime>
 <calctime>0.00313843</calctime>
 <calctime>0.00345227</calctime>
 <calctime>0.0037975</calctime>
 <calctime>0.00417725</calctime>
 <calctime>0.00459497</calctime>
 <calctime>0.00505447</calctime>
 <calctime>0.00555992</calctime>
 <calctime>0.00611591</calctime>
 <calctime>0.0067275</calctime>
 <calctime>0.00740025</calctime>
 <calctime>0.00814027</calctime>
 <calctime>0.0089543</calctime>
 <calctime>0.00984973</calctime>
 <calctime>0.0108347</calctime>
 <calctime>0.0119182</calctime>
 <calctime>0.01311</calctime>
 <calctime>0.014421</calctime>
 <calctime>0.0158631</calctime>
 <calctime>0.0174494</calctime>
 <calctime>0.0191943</calctime>
 <calctime>0.0208400</calctime>
 <calctime>0.0232252</calctime>
 <calctime>0.0255477</calctime>
 <calctime>0.0281024</calctime>
 <calctime>0.0309127</calctime>
 <calctime>0.0340039</calctime>
 <calctime>0.0374043</calctime>
 <calctime>0.04168</calctime>
 <calctime>0.0452593</calctime>
 <calctime>0.0497852</calctime>
 <calctime>0.0547637</calctime>
 <calctime>0.0602401</calctime>
 <calctime>0.06251</calctime>
 <calctime>0.0662641</calctime>
 <calctime>0.0728905</calctime>
 <calctime>0.0801795</calctime>
 <calctime>0.08334</calctime>
 <calctime>0.0881975</calctime>
 <calctime>0.0970172</calctime>
 <calctime>0.10418</calctime>
 <calctime>0.117391</calctime>
 <calctime>0.12502</calctime>
 <calctime>0.12913</calctime>
 <calctime>0.14584</calctime>
 <calctime>0.156247</calctime>
 <calctime>0.16668</calctime>
 <calctime>0.171872</calctime>
 <calctime>0.189059</calctime>
 <calctime>0.20844</calctime>
 <calctime>0.228762</calctime>
 <calctime>0.2501</calctime>
 <calctime>0.276801</calctime>
 <calctime>0.304482</calctime>
 <calctime>0.33493</calctime>
 <calctime>0.368423</calctime>
 <calctime>0.405265</calctime>
 <calctime>0.445792</calctime>
 <calctime>0.501</calctime>
 <outtime>0.02083</outtime>
 <outtime>0.04167</outtime>
 <outtime>0.06250</outtime>
 <outtime>0.08333</outtime>
 <outtime>0.10417</outtime>
 <outtime>0.12500</outtime>
 <outtime>0.14583</outtime>
 <outtime>0.16667</outtime>
 <outtime>0.20833</outtime>
 <outtime>0.25</outtime>
 <outtime>0.29167</outtime>
 <outtime>0.33333</outtime>
 <outtime>0.37500</outtime>
 <outtime>0.41667</outtime>
 <outtime>0.45833</outtime>
 <outtime>0.50</outtime>
</simulation_parameters>
